<a href="https://colab.research.google.com/github/PurvanshBarodia/Data_Science_Master/blob/main/26Feb_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [8]:
# Yes! list_ is object of list class, where array_list is a object of numpy class.

print("Datatype of list_ "+str(type(list_)))
print("Datatype of array_list "+str(type(array_list)))

Datatype of list_ <class 'list'>
Datatype of array_list <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [10]:
for i in list_:
  print(type(i))

print("_______________")

for i in array_list:
  print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
_______________
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [11]:
array_list = np.array(object = list_, dtype = int)

In [12]:
# all the element of list_ will remain of dtype str
# But in the creation of numpy array we are giving it's dtype as int
for i in list_:
  print(type(i))

print("_______________")

for i in array_list:
  print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
_______________
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [13]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape
(ii) size

In [15]:
print("Shape: "+str(num_array.shape))
print("Size: "+str(num_array.size))

Shape: (2, 3)
Size: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [16]:
arr1 = np.zeros((3,3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [18]:
arr2 = np.eye(5,5)
print(arr2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
